version: '3.7'

services:
  diplomacy.client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8000:8081'
    environment:
      - NODE_ENV=development
