export const authConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',
};

export const alertConstants = {
  ADD: 'ALERT_ADD',
  CLEAR: 'ALERT_CLEAR',
  CLEAR_ACTIVE: 'ALERT_CLEAR_ACTIVE',
  CLEAR_ALL: 'ALERT_CLEAR_ALL',
  PROMOTE_PENDING: 'ALERT_PROMOTE_PENDING',
};

export const flagConstants = {
  FLAGS_REQUEST: 'FLAGS_REQUEST',
  FLAGS_SUCCESS: 'FLAGS_SUCCESS',
  FLAGS_FAILURE: 'FLAGS_FAILURE',
};
