name: Linting
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install --dev
      - name: Run ESLint
        run: eslint 'src/**/*.{js,jsx,ts,tsx}'
