name: Linting
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install -g --dev
      - name: Run ESLint
        run: yarn run eslint 'src/**/*.{js,jsx,ts,tsx} --max-warnings 0
